version: "2"

services:
  db:
    #image: 42crunch/pixi:datastore
    image: 42crunch/pixi:mongo
    command: mongod --quiet
    container_name: pixidb
    idd: "AKIARQAYVYDDEKVOHIDE",
    key: "rHIDEnpx7o3NTR/BbwAsZRgyp+xJc1l/vVGKxAmH"
    ports:
      - "27017:27017"
      - "28017:28017"

  app:
    build: ./app
    ports:
      - "8090:8090"
    expose:
      - 8090

  # app:
  #   image: 42crunch/pixi:v4.1
  #   container_name: pixiapi
  #   ports:
  #     - "8090:8090"
  #   expose:
  #     - 8090
